disabled_rules:
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - vertical_parameter_alignment
  - closure_parameter_position
  - todo
  - trailing_comma
  - opening_brace
  - nimble_operator
  - orphaned_doc_comment
  - type_body_length
  - file_length
  - function_parameter_count
  - unused_capture_list

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - fatal_error_message
  - unneeded_parentheses_in_closure_argument
  - pattern_matching_keywords
  - array_init
  - literal_expression_end_indentation
  - joined_default_parameter
  - contains_over_first_not_nil
  - override_in_extension
  - private_action
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - sorted_first_last

line_length:
    warning: 120
    ignores_comments: true

function_body_length:
    warning: 1000 
    error: 1000

identifier_name:
  min_length:
    error: 1
  max_length:
    error: 50
  excluded:
    - id
    - pi
    - ".*Tests.swift"

type_name:
  excluded:
    - ID

nesting:
  type_level: 3